apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbear
  labels:
    app: spring-music
    tier: frontend
spec:
  # here we select the number of pods we wish to start and the selector that tells our replica set which pods it needs 
  #  to manage
  replicas: 3
  strategy:
    type: Recreate
  selector:  # Using the selector we tell our replicaset which pods to manage
    matchLabels:
      app: springbear
  template:   # here we define our PODS Specs (k8s uses go template in the background)
    metadata:
      labels:
        app: springbear
        type: canary-animals
    spec:
      containers:
        - name: bear
          image: "supergiantkir/animals:bear"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springmoose
  labels:
    app: spring-music
    tier: frontend
spec:
  # here we select the number of pods we wish to start and the selector that tells our replica set which pods it needs 
  #  to manage
  replicas: 3
  strategy:
    type: Recreate
  selector:  # Using the selector we tell our replicaset which pods to manage
    matchLabels:
      app: springmoose
  template:   # here we define our PODS Specs (k8s uses go template in the background)
    metadata:
      labels:
        app: springmoose
        type: canary-animals
    spec:
      containers:
        - name: moose
          image: "supergiantkir/animals:moose"
